### ISSUE TITLE
http-client missing

### ISSUE THREAD

**Issue by lnussel** [Firstyear/opensuse-proxy-cache#11]
The http-client directory empty and Cargo.toml refers to it. I commented it and seems to work

**Comment by Firstyear** [comment]
It doesn't work - I specifically didn't commit this yet. It works around an issue with head requests erroring incorrectly.

**Comment by lnussel** [comment]
ah, yeah. I see that now

**Comment by Firstyear** [comment]
I checked last night and there should be content in the http-client directory - I've pushed/updated last night so can you check again later ?

**Comment by Firstyear** [comment]
Fixed, it was some git shenanigans.
