### ISSUE TITLE
configurable servers?

### ISSUE THREAD

**Issue by lnussel** [Firstyear/opensuse-proxy-cache#12]
I wanted to use the proxy with download.s.d, any chance to make the server list configurable? :)

**Comment by Firstyear** [comment]
Yes, I can work on this! For now, you can use the MIRROR_CHAIN variable to override and use dl.s.d as the only upstream :)

**Comment by Firstyear** [comment]
Is this still an issue @lnussel ? You can use mirror_chain for this.

**Comment by lnussel** [comment]
I'm not using the tool anymore right now
