### ISSUE TITLE
Container exited with status 132 (missing CPU instructions set?)

### ISSUE THREAD

**Issue by vfrex** [Firstyear/opensuse-proxy-cache#13]
Greetings,

I think this is the relevant line from the logfile, using docker run: 

Jan 05 13:35:21 conmon[11580]: conmon 25f8a89e4231d9c8dae5 <ninfo>: container 11593 exited with status 132

From what I gather, exit code 132 means my CPU is missing the AVX instruction set. And indeed, running on CPUs without AVX fail with the same error code and running it on another host with AVX was successful.

Is AVX a hard requirement? It would be nice to run the proxy on a lower power host or router chip like a Celeron, which seem to lack the instruction set.

**Comment by Firstyear** [comment]
At the moment I'm only interested in building the docker image for CPU's which have these features available. You are able to build the docker image yourself if you want without these if you want :)

**Comment by vfrex** [comment]
I will give that a shot. Thank you.

**Comment by Firstyear** [comment]
No problem, let me know if you have any other issues.
