### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by codebori** [Firstyear/opensuse-proxy-cache#14]
Would it be possible to make this available for aarch64 (Raspberry Pi 4B)?

**Comment by Firstyear** [comment]
@codebori As in, you want me to publish an aarch64 container for this service?

**Comment by codebori** [comment]
If possible. I'm not a programmer. I've compiled Linux kernels, that's it. 
I tried to recompile it on my rpi, but I don't know anything about Rust and I didn't really understand what was happening.

**Comment by Firstyear** [comment]
All good, I can publish an image for this later.

**Comment by Firstyear** [comment]
@codebori I've updated the docker image for amd86/v3 and arm64 https://hub.docker.com/repository/docker/firstyear/opensuse_proxy_cache/tags?page=1&ordering=last_updated 

Hope that helps!

**Comment by edogawa23** [comment]
I'm new to docker and cannot seem to make this work on a RPi4 running Tumbleweed, I get

`docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

on dockerhub I also see only amd64 [https://hub.docker.com/r/firstyear/opensuse_proxy_cache/tags](url)

**Comment by Firstyear** [comment]
That's my mistake. I'll update it now.

**Comment by Firstyear** [comment]
https://hub.docker.com/r/firstyear/opensuse_proxy_cache/tags updated here

**Comment by edogawa23** [comment]
Thanks, awesome! :)
