### ISSUE TITLE
Doesn't work with Packman

### ISSUE THREAD

**Issue by BrianAllred** [Firstyear/opensuse-proxy-cache#17]
This project works perfectly for standard openSUSE repos, so thanks for that! But I was testing Packman (which I use for Mesa drivers), and it doesn't work.

I re-wrote 

`baseurl=https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/`

with

`baseurl=http://IPADDRESS:8080/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/`

and I get

```
Repository 'Packman' is invalid.
[packman|http://IPADDRESS:8080/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/] Valid metadata not found at specified URL
History:
 - [packman|http://IPADDRESS:8080/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/] Repository type can't be determined.
```

If it just doesn't work, that's fine, I was just curious if it was supposed to.

**Comment by Firstyear** [comment]
Theres nothing specific here in opensuse proxy cache that should present a problem here. It may be that packman are doing something different that we haven't accounted for. Everything here https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/repodata/ all looks fine generally. 

So I'd need to see the logs from the proxy cache in DEBUG mode to work this out.

Can you do:

`RUST_LOG=debug <command to run your cache`
OR
`-e RUST_LOG=debug` in your container setup

Then attempt a "zypper ref --force packman" via the proxy cache.

Once it fails, then sent me the output.

Thanks!

**Comment by BrianAllred** [comment]
Done and attached. Note the proxy host is publicly accessible, so I replaced it with `<proxy url>`.
[_suse-proxy-cache_logs.txt](https://github.com/Firstyear/opensuse-proxy-cache/files/12335676/_suse-proxy-cache_logs.txt)

**Comment by Firstyear** [comment]
@BrianAllred It's not working because I think you haven't set the upstream mirror properly. You can see this because it attempts to check

```
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Spawning upstream monitor task ...
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: resolving host="downloadcontent2.opensuse.org"
```

And 

```
0a3aec26-8bda-4a77-a862-bd1ddead6308 INFO        ┝━ ｉ [info]: 🍍  start stream -> HEAD https://downloadcontent2.opensuse.org/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/repodata/repomd.xml
0a3aec26-8bda-4a77-a862-bd1ddead6308 DEBUG       ┝━ 🐛 [debug]: reuse idle connection for ("https", downloadcontent2.opensuse.org)
```

Are you setting `MIRROR_CHAIN` here? 

You can't use this to support packman *and* the mail opensuse repos at the same time fyi. You'll need two instances.

**Comment by BrianAllred** [comment]
Ahhhhh, I see, that makes sense. I've only got one cache instance set up for the main opensuse repos at the moment. I'll go ahead and preemptively close this for now and reopen it if I run into issues with packman on my second instance.
